---
- hosts: petclinic

  tasks:
    - name: Copy JAR file into Docker container
      command: docker cp target/spring-petclinic-3.1.0-SNAPSHOT.jar petclinic:~/

    - name: Run application
      command: docker exec petclinic nohup java -jar ~/spring-petclinic-3.1.0-SNAPSHOT.jar --server.port=9090 &
  # tasks:
  #   - name: Pull Docker image
  #     docker_image:
  #       name: your-docker-image
  #       source: pull

  #   - name: Create Docker container
  #     docker_container:
  #       name: your-container-name
  #       image: your-docker-image
  #       state: started

  #   - name: Copy JAR file into Docker container
  #     docker_cp:
  #       src: path/to/your/jar/file
  #       dest: your-container-name:/path/in/container
  #       direction: to
